harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
envName: production
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - PCvk8fBVRGKvlZC_JvIKFw
phases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster
  daemonSet: false
  infraDefinitionName: k8s-production
  name: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '1'
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: simple-web-app
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster
  daemonSet: false
  infraDefinitionName: k8s-production
  name: Primary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: simple-web-app
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster
  daemonSet: false
  infraDefinitionName: k8s-production
  name: Rollback Canary
  phaseNameForRollback: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: simple-web-app
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster
  daemonSet: false
  infraDefinitionName: k8s-production
  name: Rollback Primary
  phaseNameForRollback: Primary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: simple-web-app
  statefulSet: false
templatized: false
